name: lg_rpg_controller
description: "A production-ready Controller for Liquid Galaxy RPG game "
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  dartssh2: ^2.10.0

  flutter_secure_storage: ^10.0.0

  socket_io_client: ^2.0.3+1

  uuid: ^4.4.0
  equatable: ^2.0.5
  logger: ^2.6.2

  flutter_joystick: ^0.2.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.17.1
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png
    - assets/sprites/huntress/
    - assets/sprites/water_priestess/
